config/routes.rb
Rails.application.routes.draw do

  get 'pass_resets/new'

  get 'pass_resets/edit'

  resources :proms
  resources :articles

  get 'admin/usuarios'

  get 'sessions/new'

  root 'pages#home'

  get 'admin' => 'admin#index'

  get 'secret' => 'pass_resets#answer', as: 'secret'
  post 'secret' => 'pass_resets#verify', as: 'verificar'

  
  get "catal" => 'pages#home'

  get "marcos" => 'pages#marcos'

  get 'signup' => 'users#new'
  get 'promo' => 'pages#promociones'
  get 'prod' => 'pages#productos'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'aresponse/:id' => 'pages#productos'
  get 'presponse' => 'pages#proms'

  get 'admin/editar/:id' => 'users#edit', as: 'editar'

  get 'productos' => 'articles#index'
  get 'promociones' => 'proms#index'
  get 'productos/:id' => 'articles#show'

  resources :users, :path => "normal"
  resources :pass_resets, only: [:new, :create, :edit, :update, :answer]

  resources :admin, :path => "admin"
  

end

app/views/admin/index.html.erb
<% provide(:title, "Log in as admin") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/admin/usuarios.html.erb
<%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track' => true %>

<p id="notice"><%= notice %></p>

<h1>Lista de usuarios</h1>

<ul class = "col-header">
  <li>Nombre</li>
  <li>Email</li>
</ul>

<ul>
  <% User.all.each do |user| %>
    <ul class="item-list">
      <li><%= user.name %></li>
      <li><%= user.email %></li>
     
      <li class="action-tag"><%= link_to 'Eliminar', user, method: :delete, data: { confirm: 'Estás seguro?' } %></li>
      <li class="action-tag"><%= link_to 'Editar', editar_path(user) %></li>
      <li class="action-tag"><%= link_to 'Detalles', user %></li>
    </ul>
  <% end %>
  
</ul>


<br>

<%= link_to 'Nuevo Usuario', new_user_path , class: "new_item"%>