config/routes.rb
Rails.application.routes.draw do

  get 'pass_resets/new'

  get 'pass_resets/edit'

  resources :proms
  resources :articles

  get 'admin/usuarios'

  get 'sessions/new'

  root 'pages#home'

  get 'admin' => 'admin#index'

  get 'secret' => 'pass_resets#answer', as: 'secret'
  post 'secret' => 'pass_resets#verify', as: 'verificar'

  
  get "catal" => 'pages#home'

  get "marcos" => 'pages#marcos'

  get 'signup' => 'users#new'
  get 'promo' => 'pages#promociones'
  get 'prod' => 'pages#productos'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'aresponse/:id' => 'pages#productos'
  get 'presponse' => 'pages#proms'

  get 'admin/editar/:id' => 'users#edit', as: 'editar'

  get 'productos' => 'articles#index'
  get 'promociones' => 'proms#index'
  get 'productos/:id' => 'articles#show'

  resources :users, :path => "normal"
  resources :pass_resets, only: [:new, :create, :edit, :update, :answer]

  resources :admin, :path => "admin"
  

end

app/models/prom.rb
class Prom < ActiveRecord::Base
end

app/controllers/proms_controller.rb
class PromsController < ApplicationController
  before_action :set_prom, only: [:show, :edit, :update, :destroy]

  # GET /proms
  # GET /proms.json
  def index
      @user = current_user
      @proms = Prom.all
  end

  # GET /proms/1
  # GET /proms/1.json
  def show
  end

  # GET /proms/new
  def new
    @prom = Prom.new
  end

  # GET /proms/1/edit
  def edit
  end

  # POST /proms
  # POST /proms.json
  def create
    @prom = Prom.new(prom_params)

    respond_to do |format|
      if @prom.save
        format.html { redirect_to @prom, notice: 'Promoción creada con éxito' }
        format.json { render :show, status: :created, location: @prom }
      else
        format.html { render :new }
        format.json { render json: @prom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proms/1
  # PATCH/PUT /proms/1.json
  def update
    respond_to do |format|
      if @prom.update(prom_params)
        format.html { redirect_to @prom, notice: 'Promoción modificada con éxito' }
        format.json { render :show, status: :ok, location: @prom }
      else
        format.html { render :edit }
        format.json { render json: @prom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proms/1
  # DELETE /proms/1.json
  def destroy
    @prom.destroy
    respond_to do |format|
      format.html { redirect_to proms_url, notice: 'Promoción eliminada con éxito' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prom
      @prom = Prom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prom_params
      params.require(:prom).permit(:name, :price, :image, :description, :stock, :prod_1, :prod_2, :prod_3, :prod_4, :cant_1, :cant_2, :cant_3, :cant_4, :date_start, :date_end, :valido, :url, :string_otro, :int_otro)
    end
end

app/helpers/proms_helper.rb
module PromsHelper
end

app/views/proms/_form.html.erb
<%= form_for(@prom) do |f| %>
  <% if @prom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prom.errors.count, "error") %> prohibited this prom from being saved:</h2>

      <ul>
      <% @prom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="field">
    <%= f.label :prod_1 %><br>
    <%= f.number_field :prod_1 %>
  </div>
  <div class="field">
    <%= f.label :prod_2 %><br>
    <%= f.number_field :prod_2 %>
  </div>
  <div class="field">
    <%= f.label :prod_3 %><br>
    <%= f.number_field :prod_3 %>
  </div>
  <div class="field">
    <%= f.label :prod_4 %><br>
    <%= f.number_field :prod_4 %>
  </div>
  <div class="field">
    <%= f.label :cant_1 %><br>
    <%= f.number_field :cant_1 %>
  </div>
  <div class="field">
    <%= f.label :cant_2 %><br>
    <%= f.number_field :cant_2 %>
  </div>
  <div class="field">
    <%= f.label :cant_3 %><br>
    <%= f.number_field :cant_3 %>
  </div>
  <div class="field">
    <%= f.label :cant_4 %><br>
    <%= f.number_field :cant_4 %>
  </div>
  <div class="field">
    <%= f.label :date_start %><br>
    <%= f.date_select :date_start %>
  </div>
  <div class="field">
    <%= f.label :date_end %><br>
    <%= f.date_select :date_end %>
  </div>
  <div class="field">
    <%= f.label :valido %><br>
    <%= f.number_field :valido %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :string_otro %><br>
    <%= f.text_field :string_otro %>
  </div>
  <div class="field">
    <%= f.label :int_otro %><br>
    <%= f.number_field :int_otro %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proms/edit.html.erb
<h1>Editing Prom</h1>

<%= render 'form' %>

<%= link_to 'Show', @prom %> |
<%= link_to 'Back', proms_path %>

app/views/proms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de promociones</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Image</th>
      <th>Description</th>
      <th>Stock</th>
      <th>Prod 1</th>
      <th>Prod 2</th>
      <th>Prod 3</th>
      <th>Prod 4</th>
      <th>Cant 1</th>
      <th>Cant 2</th>
      <th>Cant 3</th>
      <th>Cant 4</th>
      <th>Date start</th>
      <th>Date end</th>
      <th>Valido</th>
      <th>Url</th>
      <th>String otro</th>
      <th>Int otro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proms.each do |prom| %>
      <tr>
        <td><%= prom.name %></td>
        <td><%= prom.price %></td>
        <td><%= prom.image %></td>
        <td><%= prom.description %></td>
        <td><%= prom.stock %></td>
        <td><%= prom.prod_1 %></td>
        <td><%= prom.prod_2 %></td>
        <td><%= prom.prod_3 %></td>
        <td><%= prom.prod_4 %></td>
        <td><%= prom.cant_1 %></td>
        <td><%= prom.cant_2 %></td>
        <td><%= prom.cant_3 %></td>
        <td><%= prom.cant_4 %></td>
        <td><%= prom.date_start %></td>
        <td><%= prom.date_end %></td>
        <td><%= prom.valido %></td>
        <td><%= prom.url %></td>
        <td><%= prom.string_otro %></td>
        <td><%= prom.int_otro %></td>
        <td><%= link_to 'Detalles', prom %></td>
        <td><%= link_to 'Editar', edit_prom_path(prom) %></td>
        <td><%= link_to 'Eliminar', prom, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if !(@user.nil?) %>
  <% if (@user.admin == 1) %>
    <%= link_to 'New Prom', new_prom_path %>
  <% end %>
<% end %>

app/views/proms/new.html.erb
<h1>New Prom</h1>

<%= render 'form' %>

<%= link_to 'Back', proms_path %>

app/views/proms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @prom.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @prom.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @prom.image %>
</p>

<p>
  <strong>Description:</strong>
  <%= @prom.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @prom.stock %>
</p>

<p>
  <strong>Prod 1:</strong>
  <%= @prom.prod_1 %>
</p>

<p>
  <strong>Prod 2:</strong>
  <%= @prom.prod_2 %>
</p>

<p>
  <strong>Prod 3:</strong>
  <%= @prom.prod_3 %>
</p>

<p>
  <strong>Prod 4:</strong>
  <%= @prom.prod_4 %>
</p>

<p>
  <strong>Cant 1:</strong>
  <%= @prom.cant_1 %>
</p>

<p>
  <strong>Cant 2:</strong>
  <%= @prom.cant_2 %>
</p>

<p>
  <strong>Cant 3:</strong>
  <%= @prom.cant_3 %>
</p>

<p>
  <strong>Cant 4:</strong>
  <%= @prom.cant_4 %>
</p>

<p>
  <strong>Date start:</strong>
  <%= @prom.date_start %>
</p>

<p>
  <strong>Date end:</strong>
  <%= @prom.date_end %>
</p>

<p>
  <strong>Valido:</strong>
  <%= @prom.valido %>
</p>

<p>
  <strong>Url:</strong>
  <%= @prom.url %>
</p>

<p>
  <strong>String otro:</strong>
  <%= @prom.string_otro %>
</p>

<p>
  <strong>Int otro:</strong>
  <%= @prom.int_otro %>
</p>

<%= link_to 'Edit', edit_prom_path(@prom) %> |
<%= link_to 'Back', proms_path %>